import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import Button from '@mui/material/Button';
import { Box, Typography } from '@mui/material';
import MediaCard from '@/components/Card';
import Navbar from '@/components/Navbar';
import HomeCarousel from '@/components/HomeCarousel';
import Footer from '@/components/Footer';
import Grid from '@mui/material';
import MapSection from '../components/Map';

export default function Home() {
  return (
    <>
      <Head>
        <title>Next Mui Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <HomeCarousel />
        <Box
          sx={{
            display: 'flex',
            margin: 2,
            flexDirection: 'column',
            alignItems: 'center',
          }}
        >
          <Typography variant="h5" paddingBottom={2}>
            Come Visit us!
          </Typography>
          <MapSection />
        </Box>

        <Footer />
      </main>
    </>
  );
}
