import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Button from "@mui/material/Button";
import { Box, Typography } from "@mui/material";
import MediaCard from "@/components/Card";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Next Mui Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </Head>
      <main>
        <Navbar />
        <Box
          sx={{
            display: "flex",
            justifyContent: "space-between",
            margin: "6px 18px",
            position: "relative",
            backgroundColor: "rgba(248, 248, 239, 0.854)",
          }}
        >
          <Box>
            <Typography fontSize={20}>NavBar</Typography>
          </Box>
          <Box>
            <Typography fontSize={20}>Test</Typography>
          </Box>
        </Box>
        <Box
          sx={{
            backgroundColor: "#FFFFFF",
            display: "flex",
            flexDirection: "row",
            justifyContent: "space-between",
            alignItems: "center",
            padding: "6rem",
            gap: 4,
          }}
        >
          <Button variant="contained">Hello World</Button>
          <Button variant="contained">Hello World</Button>
          <Box>
            <MediaCard />
          </Box>
        </Box>
      </main>
    </>
  );
}
